import { ClinicalQuestion, LanguageCode } from '@medikiosk/shared-types';

export interface MultilingualText {
  en: string;
  hi?: string;
  bn?: string;
  ta?: string;
  te?: string;
  mr?: string;
  gu?: string;
  kn?: string;
  ml?: string;
  pa?: string;
  or?: string;
  as?: string;
  ur?: string;
  mai?: string;
  sat?: string;
  ks?: string;
  ne?: string;
  kok?: string;
  sd?: string;
  dgo?: string;
  mni?: string;
  brx?: string;
  sa?: string;
}

export const getLocalizedText = (textObj: MultilingualText | undefined, lang: LanguageCode): string => {
  if (!textObj) return '';
  return (textObj as any)[lang] || textObj.hi || textObj.en || '';
};

export const PROTOCOL_QUESTIONS: Record<string, any[]> = {
  // 1. Acute Chest Pain / Discomfort
  chest_pain: [
    {
      id: 'q_cp_onset',
      code: 'Q_CP_001',
      section: 'HPI • CHEST',
      prompt: {
        en: 'When did this chest pain or discomfort start?',
        hi: 'सीने में यह दर्द या परेशानी कब से शुरू हुई?',
        bn: 'বুকের এই ব্যথা বা অস্বস্তি কখন থেকে শুরু হয়েছে?',
        ta: 'இந்த நெஞ்சு வலி அல்லது அசௌகரியம் எப்போது தொடங்கியது?',
        te: 'ఈ ఛాతీ నొప్పి లేదా అసౌకర్యం ఎప్పుడు ప్రారంభమైంది?',
        mr: 'छातीत हा त्रास किंवा वेदना कधीपासून सुरू झाली?',
        gu: 'છાતીમાં આ દુખાવો અથવા અસ્વસ્થતા ક્યારે શરૂ થઈ?',
        kn: 'ಈ ಎದೆ ನೋವು ಅಥವಾ ಅಸ್ವಸ್ಥತೆ ಯಾವಾಗ ಪ್ರಾರಂಭವಾಯಿತು?',
        ml: 'ഈ നെഞ്ചുവേദന അല്ലെങ്കിൽ അസ്വസ്ഥത എപ്പോഴാണ് ആരംഭിച്ചത്?',
        as: 'বুকুৰ এই বিষ বা অস্বস্তি কেতিয়াৰ পৰা আৰম্ভ হৈছে?',
        pa: 'ਛਾਤੀ ਵਿੱਚ ਇਹ ਦਰਦ ਜਾਂ ਬੇਚੈਨੀ ਕਦੋਂ ਸ਼ੁਰੂ ਹੋਈ?',
        or: 'ଛାତିରେ ଏହି ଯନ୍ତ୍ରଣା କେବେଠାରୁ ଆରମ୍ଭ ହେଲା?',
        ur: 'سینے میں یہ درد کب سے شروع ہوا؟',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_cp_1',
          value: 'few_hours_ago',
          label: {
            en: 'A few hours ago (Last 1-6 hours)',
            hi: 'कुछ घंटे पहले (1-6 घंटे पहले)',
            bn: 'কয়েক ঘণ্টা আগে',
            ta: 'சில மணி நேரங்களுக்கு முன்',
            te: 'కొన్ని గంటల క్రితం',
            mr: 'काही तासांपूर्वी',
            gu: 'થોડા કલાકો પહેલાં',
            kn: 'ಕೆಲವು ಗಂಟೆಗಳ ಹಿಂದೆ',
            as: 'কিছু ঘণ্টা আগতে',
          },
        },
        {
          id: 'opt_cp_2',
          value: 'yesterday_night',
          label: {
            en: 'Yesterday night / early morning',
            hi: 'कल रात या सुबह से',
            bn: 'গতকাল রাতে বা ভোর থেকে',
            ta: 'நேற்று இரவு / அதிகாலை',
            te: 'నిన్న రాత్రి లేదా ఉదయం',
            mr: 'काल रात्रीपासून',
            gu: 'ગઈકાલે રાત્રેથી',
            kn: 'ನಿನ್ನೆ ರಾತ್ರಿ',
            as: 'যোৱা নিশাত',
          },
        },
        {
          id: 'opt_cp_3',
          value: 'few_days_ago',
          label: {
            en: 'A few days ago (gradual)',
            hi: 'कुछ दिनों से धीरे-धीरे',
            bn: 'কয়েক দিন ধরে',
            ta: 'சில நாட்களாக',
            te: 'కొన్ని రోజులుగా',
            mr: 'काही दिवसांपासून',
            gu: 'થોડા દિવસોથી',
            kn: 'ಕೆಲವು ದಿನಗಳಿಂದ',
            as: 'কিছুদিনৰ পৰা',
          },
        },
        {
          id: 'opt_cp_4',
          value: 'more_than_week',
          label: {
            en: 'More than a week ago (chronic)',
            hi: 'एक सप्ताह से अधिक समय से',
            bn: 'এক সপ্তাহেরও বেশি সময় ধরে',
            ta: 'ஒரு வாரத்திற்கு மேலாக',
            te: 'ఒక వారం కంటే ఎక్కువ కాలం',
            mr: 'एका आठवड्यापेक्षा जास्त काळ',
            gu: 'એક અઠવાડિયાથી વધુ સમયથી',
            kn: 'ಒಂದು ವಾರಕ್ಕಿಂತ ಹೆಚ್ಚು ಕಾಲ',
            as: 'এসপ্তাহৰো অধিক সময়ৰ পৰা',
          },
        },
      ],
      targetField: 'hpi.chest_onset',
      isRequired: true,
    },
    {
      id: 'q_cp_associated',
      code: 'Q_CP_002',
      section: 'HPI • ASSOCIATED SYMPTOMS',
      prompt: {
        en: 'Are you experiencing pain spreading to your arm/jaw, or any sweating or breathlessness?',
        hi: 'क्या दर्द बाएं हाथ या जबड़े में फैल रहा है, या पसीना/सांस फूलने जैसी समस्या है?',
        bn: 'ব্যথা কি বাম হাত বা চোয়ালে ছড়িয়ে পড়ছে, অথবা ঘাম/শ্বাসকষ্ট হচ্ছে?',
        ta: 'வலி இடது கை அல்லது தாடைக்கு பரவுகிறதா, அல்லது வியர்வை/மூச்சுத்திணறல் உள்ளதா?',
        te: 'నొప్పి ఎడమ చేయి లేదా దవడకు వ్యాపిస్తోందా, లేదా చెమటలు/శ్వాస తీసుకోవడంలో ఇబ్బంది ఉందా?',
        mr: 'वेदना डाव्या हाताकडे किंवा जबड्याकडे पसरत आहे का, किंवा घाम/श्वास लागणे असा त्रास आहे का?',
        gu: 'દુખાવો ડાબા હાથ કે જડબામાં ફેલાઈ રહ્યો છે, અથવા પરસેવો/શ્વાસ લેવામાં તકલીફ છે?',
        kn: 'ನೋವು ಎಡಗೈ ಅಥವಾ ದವಡೆಗೆ ಹರಡುತ್ತಿದೆಯೇ, ಅಥವಾ ಬೆವರು/ಉಸಿರಾಟದ ತೊಂದರೆ ಇದೆಯೇ?',
        as: 'বিষ বাওঁ হাত বা হনুৰ ফালে বিয়পিছে নেকি, বা ঘাম/উশাহ লোৱাত কষ্ট হৈছে নেকি?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_cp_assoc_emergency',
          value: 'sweating_radiation_breathlessness',
          label: {
            en: 'Yes — Radiating to left arm/jaw, heavy sweating or breathlessness',
            hi: 'हाँ — बाएं हाथ/जबड़े में दर्द, तेज पसीना या सांस फूलना',
            bn: 'হ্যাঁ — বাম হাত/চোয়ালে ব্যথা, ঘাম বা শ্বাসকষ্ট',
            ta: 'ஆம் — இடது கை/தாடை வலி, வியர்வை அல்லது மூச்சுத்திணறல்',
            te: 'అవును — ఎడమ చేయి/దవడ నొప్పి, చెమటలు లేదా శ్వాస ఆడకపోవడం',
            mr: 'होय — डाव्या हाताकडे वेदना, घाम किंवा श्वास लागणे',
            gu: 'હા — ડાબા હાથ/જડબામાં દુખાવો, પરસેવો અથવા શ્વાસ લેવામાં તકલીફ',
            kn: 'ಹೌದು — ಎಡಗೈ/ದವಡೆಗೆ ಹರಡುವ ನೋವು, ಬೆವರು ಅಥವಾ ಉಸಿರಾಟದ ತೊಂದರೆ',
            as: 'হয় — বাওঁ হাত/হনুত বিষ, ঘাম বা উশাহ চুটি হোৱা',
          },
        },
        {
          id: 'opt_cp_assoc_acidity',
          value: 'burning_acidity_burping',
          label: {
            en: 'No radiation — Burning sensation, sour burping or gas after food',
            hi: 'नहीं — केवल सीने में जलन, खट्टी डकार या भोजन के बाद गैस',
            bn: 'না — কেবল বুকে জ্বালা, টক ঢেকুর বা গ্যাসের সমস্যা',
            ta: 'இல்லை — நெஞ்செரிச்சல், புளித்த ஏப்பம் அல்லது வாயு மட்டும்',
            te: 'లేదు — కేవలం మంట, పుల్లటి తేన్పులు లేదా గ్యాస్ మాత్రమే',
            mr: 'नाही — फक्त जळजळ, आंबट ढेकर किंवा अपचन',
            gu: 'ના — ફક્ત બળતરા, ખાટા ઓડકાર અથવા ગેસ',
            kn: 'ಇಲ್ಲ — ಕೇವಲ ಎದೆ ಉರಿ, ಹುಳಿ ತೇಗು ಅಥವಾ ಗ್ಯಾಸ್ಟ್ರಿಕ್ ಮಾತ್ರ',
            as: 'নহয় — কেৱল বুকুৰ জ্বলা-পোৰা, টেঙা উগাৰ বা গেছ',
          },
        },
        {
          id: 'opt_cp_assoc_mild',
          value: 'mild_localized_discomfort',
          label: {
            en: 'Mild localized chest discomfort, no other symptoms',
            hi: 'हल्का सीमित दर्द, अन्य कोई परेशानी नहीं',
            bn: 'হালকা নির্দিষ্ট স্থানে অস্বস্তি, অন্য কোনো সমস্যা নেই',
            ta: 'லேசான வலி, வேறு எந்த அறிகுறியும் இல்லை',
            te: 'తేలికపాటి నొప్పి, ఇతర లక్షణాలు లేవు',
            mr: 'हलकासा त्रास, इतर कोणतीही लक्षणे नाहीत',
            gu: 'હળવો દુખાવો, અન્ય કોઈ લક્ષણ નથી',
            kn: 'ಸೌಮ್ಯವಾದ ನೋವು, ಬೇರೆ ಯಾವುದೇ ತೊಂದರೆ ಇಲ್ಲ',
            as: 'মৃদু বিষ, অন্য কোনো লক্ষণ নাই',
          },
        },
      ],
      targetField: 'hpi.associated_symptoms',
      isRequired: true,
    },
    {
      id: 'q_cp_character',
      code: 'Q_CP_003',
      section: 'HPI • CHARACTER',
      prompt: {
        en: 'How would you describe the sensation in your chest?',
        hi: 'सीने में किस प्रकार का दर्द या अनुभव हो रहा है?',
        bn: 'বুকে কেমন অনুভূতি হচ্ছে?',
        ta: 'நெஞ்சில் வலி எப்படி உணரப்படுகிறது?',
        te: 'ఛాతీలో నొప్పి ఎలా ఉంది?',
        mr: 'छातीत कशा प्रकारची वेदना जाणवत आहे?',
        gu: 'છાતીમાં કેવા પ્રકારનો દુખાવો થાય છે?',
        kn: 'ಎದೆಯಲ್ಲಿ ಯಾವ ರೀತಿಯ ನೋವು ಕಾಣಿಸುತ್ತಿದೆ?',
        as: 'বুকুত কেনেকুৱা বিষ অনুভৱ হৈছে?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_cp_c1',
          value: 'burning_heaviness',
          label: {
            en: 'Burning acidity / Heavy tightness',
            hi: 'जलन या भारीपन (एसिडिटी/दबाव)',
            bn: 'জ্বালা বা ভারী ভাব',
            ta: 'எரிச்சல் அல்லது பாரம்',
            te: 'మంట లేదా బరువుగా ఉండటం',
            mr: 'जळजळ किंवा जडपणा',
            gu: 'બળતરા અથવા ભારેપણું',
            kn: 'ಉರಿತ ಅಥವಾ ಭಾರವಾದ ಅನುಭವ',
            as: 'জ্বলা-পোৰা বা গধূৰ অনুভৱ',
          },
        },
        {
          id: 'opt_cp_c2',
          value: 'squeezing_crushing',
          label: {
            en: 'Severe squeezing or crushing pressure',
            hi: 'दबाव या जकड़न जैसा तीव्र दर्द',
            bn: 'চাপ বা পিষে ফেলার মতো ব্যথা',
            ta: 'கடுமையான அழுத்தம் அல்லது இறுக்கம்',
            te: 'తీవ్రమైన ఒత్తిడి లేదా బిగుతు',
            mr: 'दाब किंवा आवळल्यासारखे',
            gu: 'દબાણ અથવા ભીંચાણ જેવો દુખાવો',
            kn: 'ಹಿಂಡಿದಂತಹ ತೀವ್ರ ಒತ್ತಡದ ನೋವು',
            as: 'চেপা ধৰা তীব্ৰ বিষ',
          },
        },
        {
          id: 'opt_cp_c3',
          value: 'sharp_breathing',
          label: {
            en: 'Sharp pricking pain with deep breathing',
            hi: 'सांस लेने पर सुई जैसा चुभने वाला दर्द',
            bn: 'শ্বাস নেওয়ার সময় সূঁচ ফোটার মতো ব্যথা',
            ta: 'சுவாசிக்கும் போது குத்தும் வலி',
            te: 'శ్వాస తీసుకుంటే సూది గుచ్చినట్లు',
            mr: 'श्वास घेताना टोचल्यासारखे',
            gu: 'શ્વાસ લેતી વખતે સોય જેવો દુખાવો',
            kn: 'ಉಸಿರಾಡುವಾಗ ಚುಚ್ಚುವ ನೋವು',
            as: 'উশাহ লওঁতে বিন্ধা বিষ',
          },
        },
      ],
      targetField: 'hpi.chest_character',
      isRequired: true,
    },
  ],

  // 2. Fever, Cold & Cough
  fever: [
    {
      id: 'q_fev_duration',
      code: 'Q_FEV_001',
      section: 'HPI • FEVER',
      prompt: {
        en: 'How many days have you had this fever or cold?',
        hi: 'आपको यह बुखार, सर्दी या खांसी कितने दिनों से है?',
        bn: 'কত দিন ধরে এই জ্বর বা সর্দি-কাশি হচ্ছে?',
        ta: 'எத்தனை நாட்களாக இந்த காய்ச்சல் அல்லது சளி உள்ளது?',
        te: 'ఎన్ని రోజులుగా ఈ జ్వరం లేదా జలుబు ఉంది?',
        mr: 'हा ताप, सर्दी किंवा खोकला किती दिवसांपासून आहे?',
        gu: 'આ તાવ, શરદી કે ઉધરસ કેટલા દિવસથી છે?',
        kn: 'ಈ ಜ್ವರ, ಶೀತ ಅಥವಾ ಕೆಮ್ಮು ಎಷ್ಟು ದಿನಗಳಿಂದ ಇದೆ?',
        ml: 'ഈ പനി, ജലദോഷം അല്ലെങ്കിൽ ചുമ എത്ര ദിവസമായി ഉണ്ട്?',
        as: 'কিমান দিনৰ পৰা এই জ্বৰ, চৰ্দি বা কাহ হৈছে?',
        pa: 'ਕਿੰਨੇ ਦਿਨਾਂ ਤੋਂ ਇਹ ਬੁਖਾਰ ਜਾਂ ਖੰਘ ਹੈ?',
        or: 'କେତେ ଦିନ ଧରି ଏହି ଜ୍ୱର କିମ୍ବା ଥଣ୍ଡା ଅଛି?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_fev_1',
          value: '1_to_2_days',
          label: {
            en: '1 - 2 Days (Recent onset)',
            hi: '1 से 2 दिन (हाल ही में शुरू)',
            bn: '১ - ২ দিন',
            ta: '1 - 2 நாட்கள்',
            te: '1 - 2 రోజులు',
            mr: '१ ते २ दिवस',
            as: '১ - ২ দিন',
            kn: '1 - 2 ದಿನಗಳು',
          },
        },
        {
          id: 'opt_fev_2',
          value: '3_to_5_days',
          label: {
            en: '3 - 5 Days with body aches',
            hi: '3 से 5 दिन (शरीर दर्द के साथ)',
            bn: '৩ - ৫ দিন (গা ব্যথাসহ)',
            ta: '3 - 5 நாட்கள் (உடல் வலியுடன்)',
            te: '3 - 5 రోజులు (ఒంటి నొప్పులతో)',
            mr: '३ ते ५ दिवस (अंगदुखीसह)',
            as: '৩ - ৫ দিন (গাৰ বিষৰ সৈতে)',
            kn: '3 - 5 ದಿನಗಳು',
          },
        },
        {
          id: 'opt_fev_3',
          value: 'more_than_week',
          label: {
            en: 'More than a week / Recurrent fever',
            hi: '1 सप्ताह से अधिक या बार-बार बुखार',
            bn: 'এক সপ্তাহের বেশি / বার বার জ্বর',
            ta: 'ஒரு வாரத்திற்கு மேல் / விட்டு விட்டு காய்ச்சல்',
            te: 'వారం కంటే ఎక్కువ / మళ్లీ మళ్లీ జ్వరం',
            mr: '१ आठवड्यापेक्षा जास्त वेळ',
            as: 'এসপ্তাহৰো বেছি বা বাৰে বাৰে জ্বৰ',
            kn: 'ಒಂದು ವಾರಕ್ಕಿಂತ ಹೆಚ್ಚು',
          },
        },
      ],
      targetField: 'hpi.fever_duration',
      isRequired: true,
    },
    {
      id: 'q_fev_chills',
      code: 'Q_FEV_002',
      section: 'HPI • CHILLS & SWEATING',
      prompt: {
        en: 'Do you experience shivering chills or high body temperature spikes?',
        hi: 'क्या बुखार के साथ कंपकंपी (ठंड लगना) या अत्यधिक पसीना आता है?',
        bn: 'জ্বরের সাথে কি কাঁপুনি বা প্রচণ্ড ঘাম হচ্ছে?',
        ta: 'காய்ச்சலுடன் நடுக்கம் அல்லது கடுமையான வியர்வை வருகிறதா?',
        te: 'జ్వరంతో పాటు చలి లేదా విపరీతమైన చెమట పడుతోందా?',
        mr: 'तापासोबत हुडहुडी किंवा खूप घाम येतो का?',
        gu: 'તાવ સાથે ધ્રુજારી કે પરસેવો થાય છે?',
        kn: 'ಜ್ವರದೊಂದಿಗೆ ನಡುಕ ಅಥವಾ ಅತಿಯಾದ ಬೆವರು ಬರುತ್ತಿದೆಯೇ?',
        as: 'জ্বৰৰ লগত কঁপনি বা খুব ঘাম ওলাইছে নেকি?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_fev_chills_yes',
          value: 'high_chills',
          label: {
            en: 'Yes, severe shivering & chills (ठंड लगकर तेज बुखार)',
            hi: 'हाँ, ठंड व कंपकंपी के साथ तेज बुखार',
            bn: 'হ্যাঁ, কাঁপুনির সাথে তেজ জ্বর',
            ta: 'ஆம், நடுக்கத்துடன் கூடிய காய்ச்சல்',
            te: 'అవును, చలి జ్వరం',
            mr: 'होय, थंडी वाजून ताप',
            as: 'হয়, কঁপনি উঠি তীব্ৰ জ্বৰ',
            kn: 'ಹೌದು, ಚಳಿ ಮತ್ತು ನಡುಕ ಇದೆ',
          },
        },
        {
          id: 'opt_fev_chills_no',
          value: 'mild_warmth',
          label: {
            en: 'Mild low-grade fever with throat irritation',
            hi: 'हल्का बुखार और गले में खराश/जुकाम',
            bn: 'হালকা জ্বর ও গলা ব্যথা',
            ta: 'மிதமான காய்ச்சல் மற்றும் தொண்டை வலி',
            te: 'తేలికపాటి జ్వరం మరియు గొంతు నొప్పి',
            mr: 'हलका ताप आणि घशात खवखव',
            as: 'সাধাৰণ জ্বৰ আৰু ডিঙিৰ খচখচনি',
            kn: 'ಸಾಧಾರಣ ಜ್ವರ ಮತ್ತು ಗಂಟಲು ನೋವು',
          },
        },
      ],
      targetField: 'hpi.fever_chills',
      isRequired: true,
    },
    {
      id: 'q_fev_cough_type',
      code: 'Q_FEV_003',
      section: 'HPI • COUGH',
      prompt: {
        en: 'Is your cough dry or producing phlegm / mucus?',
        hi: 'आपकी खांसी सूखी है या बलगम (कफ) निकल रहा है?',
        bn: 'আপনার কাশি কি শুকনো নাকি কফ বের হচ্ছে?',
        ta: 'இருமல் வறட்டு இருமலா அல்லது சளி வருகிறதா?',
        te: 'దగ్గు పొడి దగ్గా లేదా కఫం వస్తోందా?',
        mr: 'खोकला कोरडा आहे की कफ पडतो?',
        gu: 'ઉધરસ સૂકી છે કે કફ નીકળે છે?',
        kn: 'ಕೆಮ್ಮು ಒಣ ಕೆಮ್ಮೇ ಅಥವಾ ಕಫ ಬರುತ್ತಿದೆಯೇ?',
        as: 'কাহটো শুকান নে কফ ওলাইছে?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_c_dry',
          value: 'dry_cough',
          label: {
            en: 'Dry hacking cough (सूखी खांसी)',
            hi: 'सूखी खांसी (बिना बलगम)',
            bn: 'শুকনো কাশি',
            ta: 'வறட்டு இருமல்',
            te: 'పొడి దగ్గు',
            mr: 'कोरडा खोकला',
            as: 'শুকান কাহ',
            kn: 'ಒಣ ಕೆಮ್ಮು',
          },
        },
        {
          id: 'opt_c_productive',
          value: 'wet_cough_sputum',
          label: {
            en: 'Productive with yellow/green phlegm',
            hi: 'गाढ़ा पीला/हरा बलगम निकल रहा है',
            bn: 'হলুদ/সবুজ কফ বের হচ্ছে',
            ta: 'மஞ்சள்/பச்சை நிற சளி வருகிறது',
            te: 'పసుపు/ఆకుపచ్చ కఫం',
            mr: 'पिवळा/हिरवा कफ पडतो',
            as: 'হালধীয়া/সেউজীয়া কফ ওলাইছে',
            kn: 'ಹಳದಿ/ಹಸಿರು ಕಫ ಬರುತ್ತದೆ',
          },
        },
        {
          id: 'opt_c_none',
          value: 'no_cough',
          label: {
            en: 'No cough, only fever & weakness',
            hi: 'खांसी नहीं है, केवल बुखार व कमजोरी',
            bn: 'কাশি নেই, কেবল জ্বর ও দুর্বলতা',
            ta: 'இருமல் இல்லை, காய்ச்சல் மட்டும்',
            te: 'దగ్గు లేదు, కేవలం జ్వరం',
            mr: 'खोकला नाही, फक्त ताप',
            as: 'কাহ নাই, কেৱল জ্বৰ আৰু দুৰ্বলতা',
            kn: 'ಕೆಮ್ಮು ಇಲ್ಲ, ಕೇವಲ ಜ್ವರ',
          },
        },
      ],
      targetField: 'hpi.cough_character',
      isRequired: true,
    },
  ],

  // 3. Acidity, Gas & Abdominal Pain
  abdominal_pain: [
    {
      id: 'q_gi_location',
      code: 'Q_GI_001',
      section: 'HPI • DIGESTIVE',
      prompt: {
        en: 'Where is your stomach discomfort located?',
        hi: 'पेट में दर्द या तकलीफ किस जगह पर सबसे ज्यादा है?',
        bn: 'পেটে ব্যথা বা অস্বস্তি কোন অংশে সবচেয়ে বেশি?',
        ta: 'வயிற்றில் வலி அல்லது அசௌகரியம் எங்கு அதிகமாக உள்ளது?',
        te: 'కడుపులో నొప్పి ఎక్కడ ఎక్కువగా ఉంది?',
        mr: 'पोटात दुखणे नेमके कुठे जास्त जाणवत आहे?',
        gu: 'પેટમાં દુખાવો કઈ જગ્યાએ સૌથી વધુ છે?',
        kn: 'ಹೊಟ್ಟೆಯಲ್ಲಿ ನೋವು ಎಲ್ಲಿ ಹೆಚ್ಚಾಗಿದೆ?',
        as: 'পেটৰ কোন অংশত বিষ আটাইতকৈ বেছি হৈছে?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_gi_upper',
          value: 'upper_epigastric',
          label: {
            en: 'Upper abdomen & chest burning (Acidity / GERD)',
            hi: 'ऊपरी पेट व छाती में जलन (अम्लपित्त / एसिडिटी)',
            bn: 'উপরের পেটে ও বুকে জ্বালা (অ্যাসিডিটি)',
            ta: 'மேல் வயிறு மற்றும் நெஞ்செரிச்சல்',
            te: 'పై కడుపు మరియు ఛాతీలో మంట',
            mr: 'वरच्या पोटात व छातीत जळजळ (अॅसिडिटी)',
            as: 'ওপৰৰ পেট আৰু বুকুৰ জ্বলা-পোৰা',
            kn: 'ಮೇಲ್ಭಾಗದ ಹೊಟ್ಟೆ ಮತ್ತು ಎದೆಯುರಿ',
          },
        },
        {
          id: 'opt_gi_lower',
          value: 'lower_abdomen_cramps',
          label: {
            en: 'Lower abdomen cramping / bloating gas',
            hi: 'निचले पेट में मरोड़, गैस और भारीपन',
            bn: 'তলপেটে টান ও গ্যাসের সমস্যা',
            ta: 'அடிவயிறு வலி மற்றும் வாயு தொல்லை',
            te: 'కడుపులో తిమ్మిరి మరియు గ్యాస్',
            mr: 'खालच्या पोटात गोळा येणे व गॅस',
            as: 'তলপেটৰ মোচৰা বিষ আৰু গেছ',
            kn: 'ಕೆಳಹೊಟ್ಟೆ ನೋವು ಮತ್ತು ಗ್ಯಾಸ್',
          },
        },
        {
          id: 'opt_gi_right',
          value: 'right_side_sharp',
          label: {
            en: 'Severe sharp pain on the right side',
            hi: 'दाहिनी तरफ तेज चुभन वाला दर्द',
            bn: 'ডান দিকে তীব্র তীক্ষ্ণ ব্যথা',
            ta: 'வலது பக்கத்தில் கடுமையான வலி',
            te: 'కుడి వైపున తీవ్రమైన నొప్పి',
            mr: 'उजव्या बाजूला तीव्र वेदना',
            as: 'সোঁফালে তীব্ৰ বিষ',
            kn: 'ಬಲಬದಿಯಲ್ಲಿ ತೀವ್ರ ಚುಚ್ಚುವ ನೋವು',
          },
        },
      ],
      targetField: 'hpi.abdominal_location',
      isRequired: true,
    },
    {
      id: 'q_gi_meals',
      code: 'Q_GI_002',
      section: 'HPI • MEAL RELATION',
      prompt: {
        en: 'Does this stomach pain increase before or after meals?',
        hi: 'क्या यह पेट दर्द खाना खाने के बाद बढ़ता है या खाली पेट?',
        bn: 'খাওয়ার আগে না পরে এই ব্যথা বাড়ে?',
        ta: 'உணவு சாப்பிடுவதற்கு முன்னா அல்லது பின்னா வலி அதிகமாகிறதா?',
        te: 'భోజనానికి ముందు లేదా తిన్న తర్వాత నొప్పి పెరుగుతుందా?',
        mr: 'जेवल्यानंतर पोटात जास्त दुखते की उपाशीपोटी?',
        gu: 'જમ્યા પછી કે ખાલી પેટે દુખાવો વધે છે?',
        kn: 'ಊಟದ ನಂತರ ಅಥವಾ ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ ನೋವು ಹೆಚ್ಚಾಗುತ್ತದೆಯೇ?',
        as: 'খোৱাৰ পিছত নে খালি পেটত বিষ বাঢ়ে?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_gi_after_meal',
          value: 'worse_after_food',
          label: {
            en: 'Worse right after eating oily / spicy food',
            hi: 'खाना या तला-भुना खाने के बाद बढ़ता है',
            bn: 'খাওয়ার পরপরই বাড়ে',
            ta: 'சாப்பிட்ட உடனே அதிகமாகிறது',
            te: 'తిన్న వెంటనే పెరుగుతుంది',
            mr: 'जेवल्यानंतर लगेच त्रास वाढतो',
            as: 'খোৱাৰ লগে লগে বাঢ়ে',
            kn: 'ಊಟದ ನಂತರ ಹೆಚ್ಚಾಗುತ್ತದೆ',
          },
        },
        {
          id: 'opt_gi_empty',
          value: 'worse_empty_stomach',
          label: {
            en: 'Worse on empty stomach, relieved by milk/food',
            hi: 'खाली पेट दर्द व जलन तेज होती है',
            bn: 'খালি পেটে ব্যথা ও জ্বালা বেশি হয়',
            ta: 'வெறும் வயிற்றில் வலி அதிகம்',
            te: 'ఖాళీ కడుపుతో ఉన్నప్పుడు ఎక్కువ',
            mr: 'उपाशीपोटी जळजळ वाढते',
            as: 'খালি পেটত জ্বলা-পোৰা বেছি হয়',
            kn: 'ಖಾಲಿ ಹೊಟ್ಟೆಯಲ್ಲಿ ಉರಿತ ಜಾಸ್ತಿ',
          },
        },
      ],
      targetField: 'hpi.meal_relation',
      isRequired: true,
    },
    {
      id: 'q_gi_bowel',
      code: 'Q_GI_003',
      section: 'HPI • BOWEL & NAUSEA',
      prompt: {
        en: 'Are you experiencing vomiting, loose motions, or constipation?',
        hi: 'क्या आपको उल्टी, दस्त (लूज मोशन) या कब्ज की शिकायत है?',
        bn: 'বমি, পাতলা পায়খানা বা কোষ্ঠকাঠিন্য আছে কি?',
        ta: 'வாந்தி, பேதி அல்லது மலச்சிக்கல் உள்ளதா?',
        te: 'వాంతులు, విరేచనాలు లేదా మలబద్ధకం ఉందా?',
        mr: 'उलटी, जुलाब किंवा बद्धकोष्ठतेचा त्रास आहे का?',
        as: 'বমি, পাতলা শৌচ বা শৌচ টান হৈছে নেকি?',
        kn: 'ವಾಂತಿ, ಭೇದಿ ಅಥವಾ ಮಲಬದ್ಧತೆ ಇದೆಯೇ?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_bowel_vomit',
          value: 'nausea_vomiting',
          label: {
            en: 'Nausea & Repeated vomiting',
            hi: 'जी मिचलाना और बार-बार उल्टी होना',
            bn: 'বমি বমি ভাব ও বমি',
            ta: 'குமட்டல் மற்றும் வாந்தி',
            te: 'వాంతులు మరియు వికారం',
            mr: 'मळमळ आणि उलट्या',
            as: 'বমি ভাব আৰু বাৰে বাৰে বমি',
            kn: 'ವಾಂತಿ ಮತ್ತು ವಾಕರಿಕೆ',
          },
        },
        {
          id: 'opt_bowel_loose',
          value: 'loose_motions_diarrhea',
          label: {
            en: 'Watery loose motions / Diarrhea',
            hi: 'पानी जैसे पतले दस्त (डायरिया)',
            bn: 'পাতলা পায়খানা বা ডায়রিয়া',
            ta: 'நீர்த்த பேதி / வயிற்றுப்போக்கு',
            te: 'నీళ్ల విరేచనాలు',
            mr: 'पातळ जुलाब',
            as: 'পানীৰ দৰে পাতলা শৌচ',
            kn: 'ನೀರಿನಂತಹ ಭೇದಿ',
          },
        },
        {
          id: 'opt_bowel_constipation',
          value: 'constipation_hard_stool',
          label: {
            en: 'Severe constipation / hard stools (Vibandha)',
            hi: 'कड़ा मल और पुराना कब्ज (विबंध)',
            bn: 'কঠিন মল ও কোষ্ঠকাঠিন্য',
            ta: 'மலச்சிக்கல்',
            te: 'మలబద్ధకం',
            mr: 'बद्धकोष्ठता व शौचास त्रास',
            as: 'টান শৌচ আৰু পুৰণি কোষ্ঠকাঠিন্য',
            kn: 'ತೀವ್ರ ಮಲಬದ್ಧತೆ',
          },
        },
      ],
      targetField: 'hpi.bowel_pattern',
      isRequired: false,
    },
  ],

  // 4. Knee & Joint Pain (Sandhivata / AYUSH / Orthopedics)
  joint_pain: [
    {
      id: 'q_jp_joints',
      code: 'Q_JP_001',
      section: 'HPI • SANDHIVATA',
      prompt: {
        en: 'Which joints are primarily painful or swollen?',
        hi: 'आपके कौन से जोड़ों में सबसे ज्यादा दर्द या सूजन है?',
        bn: 'কোন জয়েন্ট বা গাঁটে সবচেয়ে বেশি ব্যথা বা ফোলাভাব আছে?',
        ta: 'எந்த மூட்டுகளில் வலி அல்லது வீக்கம் அதிகமாக உள்ளது?',
        te: 'ఏ కీళ్లలో నొప్పి లేదా వాపు ఎక్కువగా ఉంది?',
        mr: 'तुमच्या कोणत्या सांध्यांमध्ये जास्त दुखणे किंवा सूज आहे?',
        gu: 'કયા સાંધામાં દુખાવો કે સોજો સૌથી વધુ છે?',
        kn: 'ಯಾವ ಕೀಲುಗಳಲ್ಲಿ ನೋವು ಅಥವಾ ಊತ ಹೆಚ್ಚಾಗಿದೆ?',
        as: 'কোনবোৰ গাঁঠিত বিষ বা ফুলি থকা অনুভৱ হৈছে?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_jp_knee',
          value: 'bilateral_knees',
          label: {
            en: 'Both knees (Janu Sandhigata Vata)',
            hi: 'दोनों घुटने (जानु संधिगत वात)',
            bn: 'দুই হাঁটুতে ব্যথা',
            ta: 'இரண்டு முழங்கால்கள்',
            te: 'రెండు మోకాళ్లు',
            mr: 'दोन्ही गुडघे',
            as: 'দুয়োটা আঁঠুত বিষ',
            kn: 'ಎರಡೂ ಮೊಣಕಾಲುಗಳು',
          },
        },
        {
          id: 'opt_jp_back',
          value: 'lower_back_spine',
          label: {
            en: 'Lower back & Sciatica (Katishoola / Gridhrasi)',
            hi: 'कमर, रीढ़ की हड्डी व कूल्हे का दर्द (कटिशूल / गृध्रसी)',
            bn: 'কোমর ও পিঠের ব্যথা',
            ta: 'இடுப்பு மற்றும் முதுகு வலி',
            te: 'నడుము మరియు వెన్ను నొప్పి',
            mr: 'कंबर व मणक्याचे दुखणे (कटिशूल)',
            as: 'কঁকাল আৰু পিঠিৰ বিষ',
            kn: 'ಸೊಂಟ ಮತ್ತು ಬೆನ್ನು ನೋವು',
          },
        },
        {
          id: 'opt_jp_small',
          value: 'small_joints_fingers',
          label: {
            en: 'Small finger & toe joints with swelling (Amavata)',
            hi: 'हाथ-पैर की उंगलियों के छोटे जोड़ (आमवात)',
            bn: 'হাত-পায়ের আঙুলের ছোট জয়েন্ট',
            ta: 'கை கால் விரல் மூட்டுகள் (ஆமவாதம்)',
            te: 'చేతి వేళ్లు మరియు కాలి వేళ్ల కీళ్లు',
            mr: 'हात व पायांच्या बोटांचे सांधे (आमवात)',
            as: 'হাত-ভৰিৰ আঙুলিৰ গাঁঠি (আমবাত)',
            kn: 'ಬೆರಳುಗಳ ಸಣ್ಣ ಕೀಲುಗಳು (ಆಮವಾತ)',
          },
        },
      ],
      targetField: 'hpi.joint_location',
      isRequired: true,
    },
    {
      id: 'q_jp_stiffness',
      code: 'Q_JP_002',
      section: 'HPI • MORNING STIFFNESS',
      prompt: {
        en: 'Do you feel morning stiffness and cracking sounds in joints on walking?',
        hi: 'क्या सुबह उठने पर जोड़ों में जकड़न व चलने पर कट-कट की आवाज (संधिस्फुटन) आती है?',
        bn: 'সকালে ওঠার পর কি গাঁটে শক্ত ভাব বা হাঁটার সময় শব্দ হয়?',
        ta: 'காலையில் மூட்டு இறுக்கம் அல்லது நடக்கும்போது சத்தம் வருகிறதா?',
        te: 'ఉదయాన్నే కీళ్ల బిగుతు మరియు నడిచేటప్పుడు శబ్దం వస్తోందా?',
        mr: 'सकाळी उठल्यावर सांध्यांमध्ये ताठरता व चालताना आवाज येतो का?',
        as: 'ৰাতিপুৱা গাঁঠিত আঠাৰ দৰে জঠৰতা আৰু খোজ কাঢ়োঁতে ফুট-ফুট শব্দ হয় নেকি?',
        kn: 'ಬೆಳಿಗ್ಗೆ ಕೀಲುಗಳ ಬಿಗಿತ ಮತ್ತು ನಡೆಯುವಾಗ ಶಬ್ದ ಬರುತ್ತದೆಯೇ?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_stiff_severe',
          value: 'stiffness_over_30min',
          label: {
            en: 'Yes, intense stiffness for > 30 minutes every morning',
            hi: 'हाँ, सुबह 30 मिनट से ज्यादा तेज जकड़न रहती है',
            bn: 'হ্যাঁ, সকালে ৩০ মিনিটের বেশি সময় শক্ত থাকে',
            ta: 'ஆம், காலையில் 30 நிமிடங்களுக்கு மேல் இறுக்கம்',
            te: 'అవును, ఉదయం 30 నిమిషాల కంటే ఎక్కువ బిగుతు',
            mr: 'होय, सकाळी अर्ध्या तासाहून जास्त ताठरता राहते',
            as: 'হয়, ৰাতিপুৱা ৩০ মিনিটতকৈ বেছি জঠৰ হৈ থাকে',
            kn: 'ಹೌದು, ಬೆಳಿಗ್ಗೆ 30 ನಿಮಿಷಕ್ಕಿಂತ ಹೆಚ್ಚು ಬಿಗಿತ',
          },
        },
        {
          id: 'opt_stiff_cracking',
          value: 'crepitus_cracking',
          label: {
            en: 'Mild stiffness but frequent cracking sound on bending',
            hi: 'कम जकड़न लेकिन मोड़ने पर कट-कट आवाज आती है',
            bn: 'হাঁটলে বা ভাঁজ করলে শব্দ হয়',
            ta: 'வளைக்கும்போது சத்தம் மட்டும் கேட்கிறது',
            te: 'వంచినప్పుడు శబ్దం వస్తుంది',
            mr: 'वाकवताना आवाज येतो',
            as: 'ভাঁজ কৰিলে ফুট-ফুট শব্দ ওলায়',
            kn: 'ಬಾಗಿಸಿದಾಗ ಶಬ್ದ ಮಾತ್ರ ಬರುತ್ತದೆ',
          },
        },
      ],
      targetField: 'hpi.joint_stiffness',
      isRequired: true,
    },
    {
      id: 'q_jp_severity',
      code: 'Q_JP_003',
      section: 'HPI • PAIN SCALE',
      prompt: {
        en: 'Rate your joint pain severity while walking or climbing stairs (1 to 10):',
        hi: 'चलने या सीढ़ी चढ़ने पर जोड़ों के दर्द की तीव्रता (1 से 10) चुनें:',
        bn: 'হাঁটা বা সিঁড়ি ওঠার সময় ব্যথার মাত্রা (১ থেকে ১০):',
        ta: 'நடக்கும்போது மூட்டு வலியின் அளவு (1 முதல் 10):',
        te: 'నడిచేటప్పుడు నొప్పి తీవ్రత (1 నుండి 10):',
        mr: 'चालताना किंवा पायऱ्या चढताना वेदनेची तीव्रता (१ ते १०):',
        as: 'খোজ কাঢ়োঁতে বা চিৰি উঠোঁতে বিষৰ মাত্ৰা (১ ৰ পৰা ১০):',
        kn: 'ನಡೆಯುವಾಗ ನೋವಿನ ತೀವ್ರತೆ (1 ರಿಂದ 10):',
      },
      inputType: 'NUMERIC_SCALE',
      targetField: 'hpi.joint_pain_scale',
      isRequired: true,
    },
  ],

  // 5. Skin Rash & Allergic Itching
  skin: [
    {
      id: 'q_sk_onset',
      code: 'Q_SK_001',
      section: 'HPI • TWAK ROGA',
      prompt: {
        en: 'Where is the skin rash located and how long has it been present?',
        hi: 'त्वचा पर चकत्ते या दाने किस जगह पर हैं और कितने दिनों से हैं?',
        bn: 'ত্বকে র্যাশ বা ফুসকুড়ি কোথায় আছে এবং কত দিন ধরে আছে?',
        ta: 'தோலில் தடிப்புகள் எங்கு உள்ளன மற்றும் எத்தனை நாட்களாக உள்ளன?',
        te: 'చర్మంపై దద్దుర్లు ఎక్కడ ఉన్నాయి మరియు ఎన్ని రోజులుగా ఉన్నాయి?',
        mr: 'त्वचेवर पुरळ किंवा खाज कुठे आणि किती दिवसांपासून आहे?',
        as: 'ছালত ফোঁহা বা দাগ কোন অংশত কিমান দিনৰ পৰা ওলাইছে?',
        kn: 'ಚರ್ಮದ ಮೇಲೆ ದದ್ದುಗಳು ಎಲ್ಲಿ ಮತ್ತು ಎಷ್ಟು ದಿನಗಳಿಂದ ಇವೆ?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_sk_generalized',
          value: 'generalized_body_rash',
          label: {
            en: 'All over arms, legs & body with intense itching',
            hi: 'हाथ, पैर और पूरे शरीर में तेज खुजली के साथ दाने',
            bn: 'হাত, পা ও সারা শরীরে তীব্র চুলকানি',
            ta: 'உடல் முழுவதும் கடுமையான அரிப்புடன்',
            te: 'శరీరమంతా తీవ్రమైన దురదతో',
            mr: 'हात, पाय व संपूर्ण अंगावर खाज',
            as: 'হাত, ভৰি আৰু গোটেই শৰীৰত খজুৱতি',
            kn: 'ಕೈ ಕಾಲು ಮತ್ತು ಇಡೀ ದೇಹದಲ್ಲಿ ತೀವ್ರ ತುರಿಕೆ',
          },
        },
        {
          id: 'opt_sk_localized',
          value: 'localized_patches',
          label: {
            en: 'Localized dry red scaling patches (Kushtha / Eczema)',
            hi: 'सूखे लाल चकत्ते और पपड़ी जमना (एक्जिमा / सोरायसिस)',
            bn: 'শুকনো লাল ছোপ বা আঁশযুক্ত চামড়া',
            ta: 'வறண்ட சிவப்பு தடிப்புகள் மற்றும் செதில்கள்',
            te: 'పొడి ఎర్రటి పొలుసులు',
            mr: 'कोरडे लाल चट्टे (एक्झिमा)',
            as: 'শুকান ৰঙা দাগ আৰু বাকলি ওলোৱা (খৰ)',
            kn: 'ಒಣ ಕೆಂಪು ದದ್ದುಗಳು (ಎಸ್ಜಿಮಾ)',
          },
        },
      ],
      targetField: 'hpi.rash_distribution',
      isRequired: true,
    },
    {
      id: 'q_sk_itching',
      code: 'Q_SK_002',
      section: 'HPI • ITCHING SCALE',
      prompt: {
        en: 'Rate your itching (Kandu) severity from 1 (mild) to 10 (unbearable):',
        hi: 'खुजली की तीव्रता 1 (हल्की) से 10 (असहनीय) के पैमाने पर चुनें:',
        bn: 'চুলকানির তীব্রতা ১ থেকে ১০ স্কেলে নির্বাচন করুন:',
        ta: 'அரிப்பின் தீவிரத்தை 1 முதல் 10 வரை தேர்ந்தெடுக்கவும்:',
        te: 'దురద తీవ్రతను 1 నుండి 10 స్కేలులో ఎంచుకోండి:',
        mr: 'खाजेची तीव्रता १ ते १० प्रमाणात निवडा:',
        as: 'খজুৱতিৰ মাত্ৰা ১ ৰ পৰা ১০ স্কেলত বাছক:',
        kn: 'ತುರಿಕೆಯ ತೀವ್ರತೆಯನ್ನು 1 ರಿಂದ 10 ರ ಪ್ರಮಾಣದಲ್ಲಿ ಆಯ್ಕೆಮಾಡಿ:',
      },
      inputType: 'NUMERIC_SCALE',
      targetField: 'hpi.itching_severity',
      isRequired: true,
    },
  ],

  // 6. Routine Health Consultation / AYUSH Prakriti Assessment
  ayush_assessment: [
    {
      id: 'q_ay_agni',
      code: 'Q_AY_001',
      section: 'AYUSH • AGNI & AHARA',
      prompt: {
        en: 'How would you describe your digestive appetite (Jatharagni)?',
        hi: 'आपकी भूख और पाचन शक्ति (अग्नि) कैसी रहती है?',
        bn: 'আপনার ক্ষুধা এবং হজম শক্তি কেমন থাকে?',
        ta: 'உங்கள் பசி மற்றும் செரிமான சக்தி எவ்வாறு உள்ளது?',
        te: 'మీ ఆకలి మరియు జీర్ణశక్తి ఎలా ఉంది?',
        mr: 'तुमची भूक आणि पचनशक्ती कशी आहे?',
        as: 'আপোনাৰ ভোক আৰু হজম শক্তি কেনেকুৱা থাকে?',
        kn: 'ನಿಮ್ಮ ಹಸಿವು ಮತ್ತು ಜೀರ್ಣಶಕ್ತಿ ಹೇಗಿದೆ?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_agni_sama',
          value: 'samagni_regular',
          label: {
            en: 'Regular timely appetite and smooth digestion (Samagni)',
            hi: 'समय पर सही भूख और सामान्य पाचन (समाग्नि)',
            bn: 'নিয়মিত ক্ষুধা ও স্বাভাবিক হজম (সমাগ্নি)',
            ta: 'சரியான பசி மற்றும் சீரான செரிமானம்',
            te: 'సమయానికి ఆకలి మరియు సరైన జీర్ణం',
            mr: 'वेळेवर भूक आणि चांगले पचन',
            as: 'সময়মতে নিয়মীয়া ভোক আৰু হজম',
            kn: 'ಸಮಯಕ್ಕೆ ಸರಿಯಾದ ಹಸಿವು ಮತ್ತು ಉತ್ತಮ ಜೀರ್ಣಕ್ರಿಯೆ',
          },
        },
        {
          id: 'opt_agni_manda',
          value: 'mandagni_sluggish',
          label: {
            en: 'Low appetite, heavy stomach after meals (Mandagni - Kapha)',
            hi: 'कम भूख, खाने के बाद भारीपन व सुस्ती (मंदाग्नि - कफ)',
            bn: 'কম ক্ষুধা ও খাওয়ার পর পেটে ভারী ভাব (মন্দাগ্নি)',
            ta: 'குறைந்த பசி மற்றும் சாப்பிட்ட பின் மந்தம்',
            te: 'తక్కువ ఆకలి మరియు తిన్న తర్వాత బరువుగా ఉండటం',
            mr: 'कमी भूक आणि जेवणानंतर सुस्ती',
            as: 'কম ভোক আৰু খোৱাৰ পিছত পেট গধুৰ হোৱা',
            kn: 'ಕಡಿಮೆ ಹಸಿವು ಮತ್ತು ಊಟದ ನಂತರ ಜಡತ್ವ',
          },
        },
        {
          id: 'opt_agni_tikshna',
          value: 'tikshnagni_hyperacidity',
          label: {
            en: 'Excessive sharp hunger with quick burning (Tikshnagni - Pitta)',
            hi: 'अत्यधिक तीव्र भूख, समय पर न खाने से जलन व सिरदर्द (तीक्ष्णाग्नि - पित्त)',
            bn: 'খুব বেশি ক্ষুধা ও পেটে জ্বালা (তীক্ষ্ণাগ্নি)',
            ta: 'அதிகப்படியான பசி மற்றும் நெஞ்செரிச்சல்',
            te: 'అధిక ఆకలి మరియు మంట',
            mr: 'खूप जास्त भूक व जळजळ',
            as: 'অতিমাত্ৰা ভোক আৰু জ্বলা-পোৰা',
            kn: 'ಅತಿಯಾದ ಹಸಿವು ಮತ್ತು ಉರಿತ',
          },
        },
      ],
      targetField: 'ayush.agni_type',
      isRequired: true,
    },
    {
      id: 'q_ay_nidra',
      code: 'Q_AY_002',
      section: 'AYUSH • NIDRA (SLEEP)',
      prompt: {
        en: 'How is your daily sleep quality and energy upon waking (Nidra)?',
        hi: 'आपकी नींद की गुणवत्ता और सुबह उठने पर स्फूर्ति कैसी रहती है?',
        bn: 'আপনার ঘুমের মান কেমন এবং সকালে ওঠার পর কেমন অনুভব করেন?',
        ta: 'உங்கள் தூக்கத்தின் தரம் மற்றும் காலையில் புத்துணர்ச்சி எவ்வாறு உள்ளது?',
        te: 'మీ నిద్ర నాణ్యత మరియు ఉదయం మేల్కొన్నప్పుడు శక్తి ఎలా ఉంది?',
        mr: 'तुमची झोप कशी आहे आणि सकाळी उठल्यावर ताजेतवाने वाटते का?',
        as: 'আপোনাৰ টোপনিৰ মান আৰু ৰাতিপুৱা শুই উঠি কেনে অনুভৱ হয়?',
        kn: 'ನಿಮ್ಮ ನಿದ್ರೆಯ ಗುಣಮಟ್ಟ ಮತ್ತು ಬೆಳಿಗ್ಗೆ ಏಳುವಾಗ ಶಕ್ತಿ ಹೇಗಿರುತ್ತದೆ?',
      },
      inputType: 'VOICE_OR_TOUCH',
      options: [
        {
          id: 'opt_sleep_sound',
          value: 'sound_refreshing',
          label: {
            en: '6-8 hours sound undisturbed sleep (सम्यक निद्रा)',
            hi: '6-8 घंटे गहरी और आरामदायक नींद',
            bn: '৬-৮ ঘণ্টা গভীর ঘুম',
            ta: '6-8 மணி நேரம் ஆழ்ந்த தூக்கம்',
            te: '6-8 గంటలు మంచి నిద్ర',
            mr: '६ ते ८ तास गाढ व शांत झोप',
            as: '৬-৮ ঘণ্টা গভীৰ শান্ত টোপনি',
            kn: '6-8 ಗಂಟೆಗಳ ಕಾಲ ಆರಾಮದಾಯಕ ನಿದ್ರೆ',
          },
        },
        {
          id: 'opt_sleep_disturbed',
          value: 'anidra_disturbed',
          label: {
            en: 'Disturbed light sleep, frequent waking & anxiety (Anidra - Vata)',
            hi: 'कच्ची नींद, रात में बार-बार आँख खुलना व तनाव (अनिद्रा - वात)',
            bn: 'ঘুমের ব্যাঘাত বা রাতে বারবার ঘুম ভেঙে যাওয়া',
            ta: 'தூக்கமின்மை மற்றும் பதற்றம்',
            te: 'సరిగ్గా నిద్రపట్టకపోవడం',
            mr: 'शांत झोप न लागणे व अस्वस्थता',
            as: 'টোপনি কম হোৱা বা বাৰে বাৰে সাৰ পোৱা',
            kn: 'ನಿದ್ರಾಹೀನತೆ ಮತ್ತು ತೊಂದರೆಗೊಳಗಾದ ನಿದ್ರೆ',
          },
        },
      ],
      targetField: 'ayush.nidra_quality',
      isRequired: false,
    },
  ],
};

// Aliases for fallback
PROTOCOL_QUESTIONS['general_voice'] = PROTOCOL_QUESTIONS['chest_pain'];
PROTOCOL_QUESTIONS['general_checkup'] = PROTOCOL_QUESTIONS['ayush_assessment'];

export const getQuestionsForComplaint = (complaintKey: string): ClinicalQuestion[] => {
  return (PROTOCOL_QUESTIONS[complaintKey] || PROTOCOL_QUESTIONS['chest_pain']) as ClinicalQuestion[];
};
